- name: Register stestr directory
  stat:
    path: "{{ zuul_work_dir }}/.stestr"
  register: stestr_stat

- name: Process testr artifacts
  include: process.yaml
  when:
    - stestr_stat.stat.exists

- name: Collect test-results
  synchronize:
    dest: "{{ zuul.executor.log_root }}"
    mode: pull
    src: "{{ zuul_work_dir }}/{{ item }}"
    verify_host: true
  with_items:
    - "*testr_results.html.gz"
    - "*testrepository.subunit.gz"
  when:
    - stestr_stat.stat.exists
  # some tox runs may not create test-results
  failed_when: false
