- name: Find text files to HTMLify
  find:
    paths: "{{ zuul.executor.log_root }}"
    recurse: true
    patterns:
      - "*.txt"
      - "*.txt.gz"
  register: htmlify_files

- name: HTMLify text files
  htmlify:
    input: "{{ item.path }}"
    output: "{{ item.path | regex_replace('\\.txt', '.html') }}"
  loop: "{{ htmlify_files.files }}"
  no_log: true
