- include_role:
    name: set-zuul-log-path-fact

- name: Create log directories
  file:
    path: "{{zuul_logserver_root}}/{{ zuul_log_path }}"
    state: directory
    recurse: yes
    mode: 0775

- name: Upload logs to log server
  synchronize:
    src: "{{ zuul.executor.log_root }}/"
    dest: "{{zuul_logserver_root}}/{{ zuul_log_path }}/"
    rsync_opts:
      - "--exclude=job-output.txt"
  no_log: true

# After this point there are no more logs
- name: gzip console log
  delegate_to: localhost
  archive:
    path: "{{ zuul.executor.log_root }}/job-output.txt"

- name: Upload console log
  synchronize:
    src: "{{ zuul.executor.log_root }}/job-output.txt.gz"
    dest: "{{zuul_logserver_root}}/{{ zuul_log_path }}/job-output.txt.gz"
    verify_host: true

- name: Return log URL to Zuul
  delegate_to: localhost
  zuul_return:
    data:
      zuul:
        log_url: "{{ zuul_log_url }}/{{ zuul_log_path }}/"
  when: zuul_log_url is defined
