# The apt module can not be used for this since it installs python-apt
# which can not work until this command fixes the cache.
- name: Update apt cache
  become: yes
  command: apt-get update

- name: Update yum cache
  become: yes
  command: "{{ item }}"
  with_items:
    - yum clean all
    - yum makecache
