- name: Check for ARA db
  stat:
    path: "{{ zuul.executor.work_root }}/.ara/ansible.sqlite"
  register: ara_db_stat

- name: Save the ARA database
  command: |
    cp "{{ zuul.executor.work_root }}/.ara/ansible.sqlite" \
    {{ zuul.executor.log_root }}
  when:
    - ara_db_stat.stat.exists
    - ara_save_database | bool

- name: Check for ARA install
  command: which ara
  ignore_errors: yes
  register: ara_command_type
  when: ara_db_stat.stat.exists

- name: Generate ARA html output
  command: "ara generate html {{ zuul.executor.log_root }}/ara"
  ignore_errors: yes
  when:
    - ara_command_type | succeeded
    - not ara_command_type | skipped
    - ara_generate_html | bool

- name: Compress ARA html output
  command: gzip --recursive --best {{ zuul.executor.log_root }}/ara
  ignore_errors: yes
  when: ara_compress_html | bool