- name: Run sphinx
  command:
    cmd: "{{ zuul_work_virtualenv }}/bin/sphinx-build -b {{ item }} {{ sphinx_source_dir }} {{ sphinx_build_dir }}/{{ item }}"
    chdir: "{{ zuul_work_dir }}"
  with_items: "{{ sphinx_builders }}"

- name: Check for whereto
  stat:
    path: "{{ zuul_work_virtualenv }}/bin/whereto"
    get_checksum: false
    get_mime: false
    get_md5: false
  register: whereto

# TODO(mordred) What happens with whereto if sphinx_source_dir is not doc/source?
- name: Run whereto
  command:
    cmd: "{{ whereto.stat.path }} {{ sphinx_source_dir }}/_extra/.htaccess doc/test/redirect-tests.txt"
    chdir: "{{ zuul_work_dir }}"
  when: whereto.stat.exists
