# TODO(mordred) Make this a list of known binary depends that sphinx needs
- name: Install gettext package
  package:
    name: gettext
    state: present
  become: yes

- name: Find Constraints File
  include_role:
    name: find-constraints

# Note (dmsimard): This installs doc/requirements.txt or test-requirements.txt
# if the former is not found. If neither are found, this task is skipped.
# TODO(dmsimard) Don't assume virtualenv is installed
- name: Initialize virtual environment
  pip:
    requirements: "{{ item }}"
    chdir: "{{ zuul_work_dir }}"
    virtualenv: "{{ zuul_work_virtualenv }}"
    virtualenv_python: "{{ sphinx_python }}"
    extra_args: "{{ upper_constraints | default(omit) }}"
  with_first_found:
    - files:
        - "{{ zuul_work_dir }}/doc/requirements.txt"
        - "{{ zuul_work_dir }}/test-requirements.txt"
      skip: true

- name: Install doc building packages
  pip:
    name: "{{ item }}"
    chdir: "{{ zuul_work_dir }}"
    virtualenv: "{{ zuul_work_virtualenv }}"
    virtualenv_python: "{{ sphinx_python }}"
    extra_args: "{{ upper_constraints | default(omit) }}"
  with_items: "{{ doc_building_packages }}"
